### ISSUE TITLE
Is FOL equivalent to CL logic?

### ISSUE THREAD

**Issue by Yurand2000** [Alex23087/LIS-Project#8]

**Comment by elvilio** [comment]
From [1](#one):
*That* ***every first-order theory has a coherent conservative extension*** *is regarded by some as obvious (and trivial)...*

*A positive formula, also known as a “coherent formula”, is a first-order formula built up from atoms (amongst which we include equations) using conjunction, disjunction, and existential quantification.*

Maybe there is an equivalent formulation from [2](#two) for the positive formula (coherent formula), but couldn't access the resource.

*[...] translation from FOL to CL is not necessarily constructive. The problem of provability in CL is semi-decidable.*

In [1](#one) it is then proved that another logic, called CL2, is equivalent to CL, and transofmations are provided.

From [3](#three):
*Every first-order theory has a coherent conservative extension, i.e., any first-order theory can be translated into CL, possibly with additional predicate symbols. This translation process is called “coherentisation” or, sometimes, “geometrisation”.*

For coherentisation see [4](#four).

In our case the logic need to not have negation and universal quantification because of the temporal specifications, but for each atom FOL could be used and translated, but translation could not be feasable.

## Bibliography:
1. <a name="one" href="https://doi.org/10.1017/bsl.2015.7">Dyckhoff, R., Negri, S: Geometrization of first-order logic<a/>
2. <a name="two" href="https://doi.org/10.1201/9781315273822">Rothmaler, P.: Introduction to model theory<a/>
3. <a name="three" href="https://doi.org/10.1007/s10817-022-09629-z">Janičić, P., Narboux, J.: Theorem Proving as Constraint Solving with Coherent Logic<a/>
4. <a name="four" href="https://doi.org/10.1007/978-3-319-24312-2_1">Dyckhoff, R.: Invited Talk: Coherentisation of First-Order Logic<a/>

**Comment by Yurand2000** [comment]
In syntesys, FOL != CL
